version: "3.9"

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - volume:/var/lib/mysql

# We have chosen not to insert keycloak in the docker-compose file because it requires an initial configuration
# and it is preferable to have the keycloak service active before starting the application
#  keycloak:
#    image: quay.io/keycloak/keycloak:15.0.2
#    environment:
#      - TZ=Europe/Rome
#      - KEYCLOAK_USER=root
#      - KEYCLOAK_PASSWORD=Pa55word
#      - KEYCLOAK_HOSTNAME=keycloak
#    ports:
#      - "8080:8080"
#    volumes:
#      - volume:/opt/jboss/keycloak/standalone/data

  api:
    restart: always
    environment:
#      - KEYCLOAK_HOST=keycloak
#      - KEYCLOAK_PORT=8080
      - TZ=Europe/Rome
      - DATABASE_URL=mysql://${DB_USERNAME}:${DB_PASSWORD}@mysql:3306/${DB_DATABASE}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mysql
#      - keycloak
    links:
      - mysql
#      - keycloak

volumes:
  volume:
