version: "3.9"

services:
  mysql:
    container_name: myapp-prod-mysql
  api:
    container_name: myapp-prod-api
    build:
      context: ../..
      dockerfile: ./docker/production/Dockerfile.prod
    env_file: .env
