FROM node:15-alpine
WORKDIR /usr/app

ENV APP_PORT=8000
ENV APP_ENV=development

# Copy app files
COPY . .
RUN mv ./docker/scripts ./scripts

RUN chmod -R +x ./scripts/
RUN apk add --no-cache --upgrade bash # Add bash to run scripts

RUN npm install
RUN npx prisma generate

EXPOSE ${APP_PORT}
CMD ["bash", "./scripts/start.sh"]
