FROM node:latest
WORKDIR /usr/app

COPY ./package.json ./
COPY ./tsconfig.json ./
COPY ./prisma/schema.prisma ./prisma/schema.prisma
COPY ./src ./src

RUN npm install
RUN npx prisma generate
EXPOSE ${APP_PORT}

ENV TZ=${APP_TIMEZONE}
CMD ["npm","start"]
